spring.application.name=BookReview
# H2への接続設定（メモリモード：アプリを落とすとデータが消えます）
spring.datasource.url=jdbc:h2:mem:bookdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# H2 Consoleの設定（ブラウザでDBが見れるツール）
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Hibernateの設定（SQLをコンソールに表示して学習しやすくする）
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

# Hibernateがテーブルを自動作成した後にSQLを実行するように設定
spring.jpa.defer-datasource-initialization=true

spring.sql.init.mode=always

server.port=${PORT:8080}